In [184]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# 1-Loading Data

In [185]:
data = {
    'Order_ID': [1001, 1002, 1003, 1004, 1005, 1003, 1006, 1007, 1008, 1005,1010],
    'Product': ['Smartphone', 'Laptop', 'Headphones', 'Smartphone', 'Tablet', 
               'Headphones', np.nan,'Smartwatch', 'Smartphone', 'Tablet','Mouse'],
    'Price': ['$599.99', '€899', '150 USD', '$599.99', '300 GBP', 
              '150 USD', '250.50', '599.99', '300 GBP', '300','15$'],
    'Quantity': ['2', '1', '5 units', '7', '2', 
                 '5 units', '4', '3', 'N/A', '2','1'],
    'Order_Date': ['2023-01-15', '2023/02/20', '2023-03-25', '2023-01-15', 
                   '2023-05-05', '2023/06/15', '2023-07-20', 'December 25th 2023', '2023/08/25', '2023-05-05','2023/08/28'],
    'Customer_Email': ['alice@example.com', 'bob@example.com', 'charlie@example.com', 
                       'alice@example.com', 'eve@example.com', 'charlie@example.com', 
                       'hany@example.com', 'david@example.com', 'hank@example.com', 'eve@example.com','mickel@example.com']
}

In [186]:
df=pd.DataFrame(data)
df

,Order_ID,Product,Price,Quantity,Order_Date,Customer_Email
0,1001,Smartphone,$599.99,2,2023-01-15,alice@example.com
1,1002,Laptop,€899,1,2023/02/20,bob@example.com
2,1003,Headphones,150 USD,5 units,2023-03-25,charlie@example.com
3,1004,Smartphone,$599.99,7,2023-01-15,alice@example.com
4,1005,Tablet,300 GBP,2,2023-05-05,eve@example.com
5,1003,Headphones,150 USD,5 units,2023/06/15,charlie@example.com
6,1006,NaN,250.50,4,2023-07-20,hany@example.com
7,1007,Smartwatch,599.99,3,December 25th 2023,david@example.com
8,1008,Smartphone,300 GBP,N/A,2023/08/25,hank@example.com
9,1005,Tablet,300,2,2023-05-05,eve@example.com
10,1010,Mouse,15$,1,2023/08/28,mickel@example.com

# 2-Exploring a DataFrame

In [187]:
df.head(7)

   Order_ID     Product    Price Quantity  Order_Date       Customer_Email
0      1001  Smartphone  $599.99        2  2023-01-15    alice@example.com
1      1002      Laptop     €899        1  2023/02/20      bob@example.com
2      1003  Headphones  150 USD  5 units  2023-03-25  charlie@example.com
3      1004  Smartphone  $599.99        7  2023-01-15    alice@example.com
4      1005      Tablet  300 GBP        2  2023-05-05      eve@example.com
5      1003  Headphones  150 USD  5 units  2023/06/15  charlie@example.com
6      1006         NaN   250.50        4  2023-07-20     hany@example.com

In [188]:
df.tail()

,Order_ID,Product,Price,Quantity,Order_Date,Customer_Email
6,1006,NaN,250.50,4,2023-07-20,hany@example.com
7,1007,Smartwatch,599.99,3,December 25th 2023,david@example.com
8,1008,Smartphone,300 GBP,N/A,2023/08/25,hank@example.com
9,1005,Tablet,300,2,2023-05-05,eve@example.com
10,1010,Mouse,15$,1,2023/08/28,mickel@example.com

In [189]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        11 non-null     int64
 1   Product         10 non-null     object
 2   Price           11 non-null     object
 3   Quantity        11 non-null     object
 4   Order_Date      11 non-null     object
 5   Customer_Email  11 non-null     object
dtypes: int64(1), object(5)
memory usage: 660.0+ bytes

In [190]:
df.describe()

          Order_ID
count    11.000000
mean   1004.909091
std       2.700168
min    1001.000000
25%    1003.000000
50%    1005.000000
75%    1006.500000
max    1010.000000

In [191]:
df.shape

(11, 6)

In [192]:
df.columns

Index(['Order_ID', 'Product', 'Price', 'Quantity', 'Order_Date',
       'Customer_Email'],
      dtype='object')

In [193]:
df.values

array([[1001, 'Smartphone', '$599.99', '2', '2023-01-15',
        'alice@example.com'],
       [1002, 'Laptop', '€899', '1', '2023/02/20', 'bob@example.com'],
       [1003, 'Headphones', '150 USD', '5 units', '2023-03-25',
        'charlie@example.com'],
       [1004, 'Smartphone', '$599.99', '7', '2023-01-15',
        'alice@example.com'],
       [1005, 'Tablet', '300 GBP', '2', '2023-05-05', 'eve@example.com'],
       [1003, 'Headphones', '150 USD', '5 units', '2023/06/15',
        'charlie@example.com'],
       [1006, nan, '250.50', '4', '2023-07-20', 'hany@example.com'],
       [1007, 'Smartwatch', '599.99', '3', 'December 25th 2023',
        'david@example.com'],
       [1008, 'Smartphone', '300 GBP', 'N/A', '2023/08/25',
        'hank@example.com'],
       [1005, 'Tablet', '300', '2', '2023-05-05', 'eve@example.com'],
       [1010, 'Mouse', '15$', '1', '2023/08/28', 'mickel@example.com']],
      dtype=object)

In [194]:
df.index

RangeIndex(start=0, stop=11, step=1)

In [195]:
df['Product'].value_counts()

Product
Smartphone    3
Headphones    2
Tablet        2
Laptop        1
Smartwatch    1
Mouse         1
Name: count, dtype: int64

# 3-Handling Data

## 3-1 Handl Type of Columns

In [196]:
df.dtypes

Order_ID           int64
Product           object
Price             object
Quantity          object
Order_Date        object
Customer_Email    object
dtype: object

In [197]:
for col in df.columns:
    print(df[col].value_counts())

Order_ID
1003    2
1005    2
1001    1
1002    1
1004    1
1006    1
1007    1
1008    1
1010    1
Name: count, dtype: int64
Product
Smartphone    3
Headphones    2
Tablet        2
Laptop        1
Smartwatch    1
Mouse         1
Name: count, dtype: int64
Price
$599.99    2
150 USD    2
300 GBP    2
€899       1
250.50     1
599.99     1
300        1
15$        1
Name: count, dtype: int64
Quantity
2          3
1          2
5 units    2
7          1
4          1
3          1
N/A        1
Name: count, dtype: int64
Order_Date
2023-01-15            2
2023-05-05            2
2023/02/20            1
2023-03-25            1
2023/06/15            1
2023-07-20            1
December 25th 2023    1
2023/08/25            1
2023/08/28            1
Name: count, dtype: int64
Customer_Email
alice@example.com      2
charlie@example.com    2
eve@example.com        2
bob@example.com        1
hany@example.com       1
david@example.com      1
hank@example.com       1
mickel@example.com     1
Name: count, dtype: int64

In [198]:
df['Price']=df['Price'].str.replace(r'[^0-9.]', '', regex=True)
df['Price']=df['Price'].astype('float64')
df['Price']

0     599.99
1     899.00
2     150.00
3     599.99
4     300.00
5     150.00
6     250.50
7     599.99
8     300.00
9     300.00
10     15.00
Name: Price, dtype: float64

In [199]:
df['Quantity']=df['Quantity'].str.replace(r'[^0-9.]', '', regex=True)
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce').astype('Int64')  # 'Int64' handles NaN
df['Quantity']

0        2
1        1
2        5
3        7
4        2
5        5
6        4
7        3
8     <NA>
9        2
10       1
Name: Quantity, dtype: Int64

## 3-2 Handl Data

In [200]:
df['Order_Date']=pd.to_datetime(df['Order_Date'],format='mixed')
df['Order_Date']

0    2023-01-15
1    2023-02-20
2    2023-03-25
3    2023-01-15
4    2023-05-05
5    2023-06-15
6    2023-07-20
7    2023-12-25
8    2023-08-25
9    2023-05-05
10   2023-08-28
Name: Order_Date, dtype: datetime64[ns]

## 3-3 Handl Missing Values

In [201]:
df.isnull().sum()

Order_ID          0
Product           1
Price             0
Quantity          1
Order_Date        0
Customer_Email    0
dtype: int64

In [202]:
df.fillna({'Quantity':int(df['Quantity'].mean())},inplace=True)
df.dropna(subset='Product',axis=0,inplace=True)
df

    Order_ID     Product   Price  Quantity Order_Date       Customer_Email
0       1001  Smartphone  599.99         2 2023-01-15    alice@example.com
1       1002      Laptop  899.00         1 2023-02-20      bob@example.com
2       1003  Headphones  150.00         5 2023-03-25  charlie@example.com
3       1004  Smartphone  599.99         7 2023-01-15    alice@example.com
4       1005      Tablet  300.00         2 2023-05-05      eve@example.com
5       1003  Headphones  150.00         5 2023-06-15  charlie@example.com
7       1007  Smartwatch  599.99         3 2023-12-25    david@example.com
8       1008  Smartphone  300.00         3 2023-08-25     hank@example.com
9       1005      Tablet  300.00         2 2023-05-05      eve@example.com
10      1010       Mouse   15.00         1 2023-08-28   mickel@example.com

## 3-4 Duplicates

In [203]:
print(df[df.duplicated()])

   Order_ID Product  Price  Quantity Order_Date   Customer_Email
9      1005  Tablet  300.0         2 2023-05-05  eve@example.com

In [204]:
df.drop_duplicates(inplace = True)

In [205]:
df.drop(index=5,axis=1,inplace=True)

In [206]:
df.reset_index(drop=True,inplace=True)

In [207]:
df

   Order_ID     Product   Price  Quantity Order_Date       Customer_Email
0      1001  Smartphone  599.99         2 2023-01-15    alice@example.com
1      1002      Laptop  899.00         1 2023-02-20      bob@example.com
2      1003  Headphones  150.00         5 2023-03-25  charlie@example.com
3      1004  Smartphone  599.99         7 2023-01-15    alice@example.com
4      1005      Tablet  300.00         2 2023-05-05      eve@example.com
5      1007  Smartwatch  599.99         3 2023-12-25    david@example.com
6      1008  Smartphone  300.00         3 2023-08-25     hank@example.com
7      1010       Mouse   15.00         1 2023-08-28   mickel@example.com

# 4- Sorting

In [208]:
df.sort_values('Price')

   Order_ID     Product   Price  Quantity Order_Date       Customer_Email
7      1010       Mouse   15.00         1 2023-08-28   mickel@example.com
2      1003  Headphones  150.00         5 2023-03-25  charlie@example.com
4      1005      Tablet  300.00         2 2023-05-05      eve@example.com
6      1008  Smartphone  300.00         3 2023-08-25     hank@example.com
0      1001  Smartphone  599.99         2 2023-01-15    alice@example.com
3      1004  Smartphone  599.99         7 2023-01-15    alice@example.com
5      1007  Smartwatch  599.99         3 2023-12-25    david@example.com
1      1002      Laptop  899.00         1 2023-02-20      bob@example.com

In [209]:
df.sort_values('Quantity',ascending=False)

   Order_ID     Product   Price  Quantity Order_Date       Customer_Email
3      1004  Smartphone  599.99         7 2023-01-15    alice@example.com
2      1003  Headphones  150.00         5 2023-03-25  charlie@example.com
5      1007  Smartwatch  599.99         3 2023-12-25    david@example.com
6      1008  Smartphone  300.00         3 2023-08-25     hank@example.com
0      1001  Smartphone  599.99         2 2023-01-15    alice@example.com
4      1005      Tablet  300.00         2 2023-05-05      eve@example.com
1      1002      Laptop  899.00         1 2023-02-20      bob@example.com
7      1010       Mouse   15.00         1 2023-08-28   mickel@example.com

In [210]:
df.sort_values(['Price','Order_Date'])

   Order_ID     Product   Price  Quantity Order_Date       Customer_Email
7      1010       Mouse   15.00         1 2023-08-28   mickel@example.com
2      1003  Headphones  150.00         5 2023-03-25  charlie@example.com
4      1005      Tablet  300.00         2 2023-05-05      eve@example.com
6      1008  Smartphone  300.00         3 2023-08-25     hank@example.com
0      1001  Smartphone  599.99         2 2023-01-15    alice@example.com
3      1004  Smartphone  599.99         7 2023-01-15    alice@example.com
5      1007  Smartwatch  599.99         3 2023-12-25    david@example.com
1      1002      Laptop  899.00         1 2023-02-20      bob@example.com

In [211]:
df.sort_values(['Price','Order_Date'],ascending=[True,True])

   Order_ID     Product   Price  Quantity Order_Date       Customer_Email
7      1010       Mouse   15.00         1 2023-08-28   mickel@example.com
2      1003  Headphones  150.00         5 2023-03-25  charlie@example.com
4      1005      Tablet  300.00         2 2023-05-05      eve@example.com
6      1008  Smartphone  300.00         3 2023-08-25     hank@example.com
0      1001  Smartphone  599.99         2 2023-01-15    alice@example.com
3      1004  Smartphone  599.99         7 2023-01-15    alice@example.com
5      1007  Smartwatch  599.99         3 2023-12-25    david@example.com
1      1002      Laptop  899.00         1 2023-02-20      bob@example.com

## 5- Selection

In [212]:
df['Quantity']

0    2
1    1
2    5
3    7
4    2
5    3
6    3
7    1
Name: Quantity, dtype: Int64

In [213]:
df['Quantity'].max()

7

In [214]:
df['Quantity'].idxmax()

3

In [215]:
df['Price'].min()

15.0

In [216]:
df['Price'].idxmin()

7

In [217]:
df['Product'].nunique

<bound method IndexOpsMixin.nunique of 0    Smartphone
1        Laptop
2    Headphones
3    Smartphone
4        Tablet
5    Smartwatch
6    Smartphone
7         Mouse
Name: Product, dtype: object>

In [218]:
df[['Customer_Email','Product']]

        Customer_Email     Product
0    alice@example.com  Smartphone
1      bob@example.com      Laptop
2  charlie@example.com  Headphones
3    alice@example.com  Smartphone
4      eve@example.com      Tablet
5    david@example.com  Smartwatch
6     hank@example.com  Smartphone
7   mickel@example.com       Mouse

In [219]:
df.loc[1:3,['Order_ID','Product','Price']]

   Order_ID     Product   Price
1      1002      Laptop  899.00
2      1003  Headphones  150.00
3      1004  Smartphone  599.99

In [220]:
df.iloc[:,1:3]

      Product   Price
0  Smartphone  599.99
1      Laptop  899.00
2  Headphones  150.00
3  Smartphone  599.99
4      Tablet  300.00
5  Smartwatch  599.99
6  Smartphone  300.00
7       Mouse   15.00

In [221]:
df.iloc[0:4,4:6]

  Order_Date       Customer_Email
0 2023-01-15    alice@example.com
1 2023-02-20      bob@example.com
2 2023-03-25  charlie@example.com
3 2023-01-15    alice@example.com

In [222]:
df.iloc[1:5,-6:]

   Order_ID     Product   Price  Quantity Order_Date       Customer_Email
1      1002      Laptop  899.00         1 2023-02-20      bob@example.com
2      1003  Headphones  150.00         5 2023-03-25  charlie@example.com
3      1004  Smartphone  599.99         7 2023-01-15    alice@example.com
4      1005      Tablet  300.00         2 2023-05-05      eve@example.com

In [223]:
d=df.set_index('Product')
d

            Order_ID   Price  Quantity Order_Date       Customer_Email
Product
Smartphone      1001  599.99         2 2023-01-15    alice@example.com
Laptop          1002  899.00         1 2023-02-20      bob@example.com
Headphones      1003  150.00         5 2023-03-25  charlie@example.com
Smartphone      1004  599.99         7 2023-01-15    alice@example.com
Tablet          1005  300.00         2 2023-05-05      eve@example.com
Smartwatch      1007  599.99         3 2023-12-25    david@example.com
Smartphone      1008  300.00         3 2023-08-25     hank@example.com
Mouse           1010   15.00         1 2023-08-28   mickel@example.com

In [224]:
d.loc[['Smartwatch','Mouse']]

            Order_ID   Price  Quantity Order_Date      Customer_Email
Product
Smartwatch      1007  599.99         3 2023-12-25   david@example.com
Mouse           1010   15.00         1 2023-08-28  mickel@example.com

In [225]:
d.loc[('Smartphone','Mouse'),('Price','Customer_Email')]

             Price      Customer_Email
Product
Smartphone  599.99   alice@example.com
Smartphone  599.99   alice@example.com
Smartphone  300.00    hank@example.com
Mouse        15.00  mickel@example.com

In [226]:
d.loc['Tablet']

Order_ID                         1005
Price                           300.0
Quantity                            2
Order_Date        2023-05-05 00:00:00
Customer_Email        eve@example.com
Name: Tablet, dtype: object

In [227]:
d.sort_index()

            Order_ID   Price  Quantity Order_Date       Customer_Email
Product
Headphones      1003  150.00         5 2023-03-25  charlie@example.com
Laptop          1002  899.00         1 2023-02-20      bob@example.com
Mouse           1010   15.00         1 2023-08-28   mickel@example.com
Smartphone      1001  599.99         2 2023-01-15    alice@example.com
Smartphone      1004  599.99         7 2023-01-15    alice@example.com
Smartphone      1008  300.00         3 2023-08-25     hank@example.com
Smartwatch      1007  599.99         3 2023-12-25    david@example.com
Tablet          1005  300.00         2 2023-05-05      eve@example.com

In [228]:
d.iloc[1:4,:]

            Order_ID   Price  Quantity Order_Date       Customer_Email
Product
Laptop          1002  899.00         1 2023-02-20      bob@example.com
Headphones      1003  150.00         5 2023-03-25  charlie@example.com
Smartphone      1004  599.99         7 2023-01-15    alice@example.com

In [229]:
d.iloc[-9:,2:4]

            Quantity Order_Date
Product
Smartphone         2 2023-01-15
Laptop             1 2023-02-20
Headphones         5 2023-03-25
Smartphone         7 2023-01-15
Tablet             2 2023-05-05
Smartwatch         3 2023-12-25
Smartphone         3 2023-08-25
Mouse              1 2023-08-28

In [230]:
d.iloc[-9:-7,2:5]

            Quantity Order_Date     Customer_Email
Product
Smartphone         2 2023-01-15  alice@example.com

# 6- Filteration

In [231]:
df['Quantity']>2

0    False
1    False
2     True
3     True
4    False
5     True
6     True
7    False
Name: Quantity, dtype: boolean

In [232]:
df[df['Quantity']>2]

   Order_ID     Product   Price  Quantity Order_Date       Customer_Email
2      1003  Headphones  150.00         5 2023-03-25  charlie@example.com
3      1004  Smartphone  599.99         7 2023-01-15    alice@example.com
5      1007  Smartwatch  599.99         3 2023-12-25    david@example.com
6      1008  Smartphone  300.00         3 2023-08-25     hank@example.com

In [233]:
df[df['Product']=="Tablet"]

   Order_ID Product  Price  Quantity Order_Date   Customer_Email
4      1005  Tablet  300.0         2 2023-05-05  eve@example.com

In [234]:
df[df["Order_Date"] > '2023-03-25']

   Order_ID     Product   Price  Quantity Order_Date      Customer_Email
4      1005      Tablet  300.00         2 2023-05-05     eve@example.com
5      1007  Smartwatch  599.99         3 2023-12-25   david@example.com
6      1008  Smartphone  300.00         3 2023-08-25    hank@example.com
7      1010       Mouse   15.00         1 2023-08-28  mickel@example.com

In [235]:
i = df["Product"] == "Smartphone" 
j = df["Quantity"] > 2 
df[i & j]

   Order_ID     Product   Price  Quantity Order_Date     Customer_Email
3      1004  Smartphone  599.99         7 2023-01-15  alice@example.com
6      1008  Smartphone  300.00         3 2023-08-25   hank@example.com

In [236]:
df[df["Product"].isin(["Smartphone", "Tablet"])]

   Order_ID     Product   Price  Quantity Order_Date     Customer_Email
0      1001  Smartphone  599.99         2 2023-01-15  alice@example.com
3      1004  Smartphone  599.99         7 2023-01-15  alice@example.com
4      1005      Tablet  300.00         2 2023-05-05    eve@example.com
6      1008  Smartphone  300.00         3 2023-08-25   hank@example.com

# 7- Adding New Columns

In [237]:
df['Customer Name']=df['Customer_Email'].str.split('@').str[0]
df['Customer Name']

0      alice
1        bob
2    charlie
3      alice
4        eve
5      david
6       hank
7     mickel
Name: Customer Name, dtype: object

# 8- Summery statistics

In [238]:
df['Price'].mean()

432.99625000000003

In [239]:
df['Quantity'].std()

2.0701966780270626

In [240]:
df['Quantity'].cumsum()

0     2
1     3
2     8
3    15
4    17
5    20
6    23
7    24
Name: Quantity, dtype: Int64

In [241]:
df['Quantity'].cummin()

0    2
1    1
2    1
3    1
4    1
5    1
6    1
7    1
Name: Quantity, dtype: Int64

# 9- Aggregating

In [242]:
df.groupby('Product')['Price'].mean()

Product
Headphones    150.000000
Laptop        899.000000
Mouse          15.000000
Smartphone    499.993333
Smartwatch    599.990000
Tablet        300.000000
Name: Price, dtype: float64

In [243]:
df['Price'].agg(['min','mean','std'])

min      15.000000
mean    432.996250
std     290.566929
Name: Price, dtype: float64

In [244]:
df.groupby('Quantity')['Price'].agg(['min','mean','std'])

             min     mean         std
Quantity
1          15.00  457.000  625.082395
2         300.00  449.995  212.124963
3         300.00  449.995  212.124963
5         150.00  150.000         NaN
7         599.99  599.990         NaN

In [245]:
df.groupby('Product').agg({
    'Quantity': ['mean', 'max', 'min'],
    'Price': 'mean',
})

           Quantity               Price
               mean max min        mean
Product
Headphones      5.0   5   5  150.000000
Laptop          1.0   1   1  899.000000
Mouse           1.0   1   1   15.000000
Smartphone      4.0   7   2  499.993333
Smartwatch      3.0   3   3  599.990000
Tablet          2.0   2   2  300.000000

# 10- Pivot & Pivot Table

In [246]:
#Reshape data by specifying unique index/column pairs
p_v=df.iloc[:3,:].pivot(values='Quantity',index='Customer Name',columns='Product')
p_v

Product        Headphones  Laptop  Smartphone
Customer Name
alice                <NA>    <NA>           2
bob                  <NA>       1        <NA>
charlie                 5    <NA>        <NA>

In [247]:
#From long to wide
p_v=df.pivot_table(values='Price',index='Product',aggfunc='mean')
p_v

                 Price
Product
Headphones  150.000000
Laptop      899.000000
Mouse        15.000000
Smartphone  499.993333
Smartwatch  599.990000
Tablet      300.000000

In [248]:
p_v=df.pivot_table(values='Price',index=['Product','Order_ID'],aggfunc='mean', margins=True)
p_v

                         Price
Product    Order_ID
Headphones 1003      150.00000
Laptop     1002      899.00000
Mouse      1010       15.00000
Smartphone 1001      599.99000
           1004      599.99000
           1008      300.00000
Smartwatch 1007      599.99000
Tablet     1005      300.00000
All                  432.99625

In [249]:
p_v.loc[('Smartwatch',1007),:]

Price    599.99
Name: (Smartwatch, 1007), dtype: float64

In [250]:
p_v.loc[[('Smartwatch',1007),('Tablet',1005)],:]

                      Price
Product    Order_ID
Smartwatch 1007      599.99
Tablet     1005      300.00

In [251]:
p_v=df.pivot_table(values='Quantity',index='Product',aggfunc=[np.max,np.min])
p_v

                max      min
           Quantity Quantity
Product
Headphones        5        5
Laptop            1        1
Mouse             1        1
Smartphone        7        2
Smartwatch        3        3
Tablet            2        2

In [252]:
p_v.loc['Laptop':'Smartphone',:]

                max      min
           Quantity Quantity
Product
Laptop            1        1
Mouse             1        1
Smartphone        7        2

In [253]:
p_v=df.pivot_table(values='Quantity',index='Customer Name',columns='Product',margins=True,margins_name='Total',fill_value=0)
p_v

Product,Headphones,Laptop,Mouse,Smartphone,Smartwatch,Tablet,Total
Customer Name,,,,,,,
alice,0.0,0.0,0.0,4.5,0.0,0.0,4.5
bob,0.0,1.0,0.0,0.0,0.0,0.0,1.0
charlie,5.0,0.0,0.0,0.0,0.0,0.0,5.0
david,0.0,0.0,0.0,0.0,3.0,0.0,3.0
eve,0.0,0.0,0.0,0.0,0.0,2.0,2.0
hank,0.0,0.0,0.0,3.0,0.0,0.0,3.0
mickel,0.0,0.0,1.0,0.0,0.0,0.0,1.0
Total,5.0,1.0,1.0,4.0,3.0,2.0,3.0

In [254]:
p_v=df.pivot_table(values='Quantity',index='Customer Name',columns='Product',aggfunc='max',margins=True,margins_name='Total',fill_value=0)
p_v

Product,Headphones,Laptop,Mouse,Smartphone,Smartwatch,Tablet,Total
Customer Name,,,,,,,
alice,0,0,0,7,0,0,7
bob,0,1,0,0,0,0,1
charlie,5,0,0,0,0,0,5
david,0,0,0,0,3,0,3
eve,0,0,0,0,0,2,2
hank,0,0,0,3,0,0,3
mickel,0,0,1,0,0,0,1
Total,5,1,1,7,3,2,7

In [255]:
p_v.loc['bob':'eve',['Headphones','Laptop']]

Product        Headphones  Laptop
Customer Name
bob                     0       1
charlie                 5       0
david                   0       0
eve                     0       0

In [256]:
p_v=df.pivot_table(index='Order_ID',values='Quantity')
p_v

          Quantity
Order_ID
1001           2.0
1002           1.0
1003           5.0
1004           7.0
1005           2.0
1007           3.0
1008           3.0
1010           1.0

In [257]:
p_v.iloc[1:3,:]

          Quantity
Order_ID
1002           1.0
1003           5.0

In [258]:
p_v.set_index('Quantity').sort_index()

Empty DataFrame
Columns: []
Index: [1.0, 1.0, 2.0, 2.0, 3.0, 3.0, 5.0, 7.0]

# 11- Merging DataFrames

In [259]:
data={'City':['LA','Madrid','NewYork'],'Order_ID':[[1001,1002,1003],[1004,1005],[1008,1010,1007]]}
df1=pd.DataFrame(data)
df1.head()

      City            Order_ID
0       LA  [1001, 1002, 1003]
1   Madrid        [1004, 1005]
2  NewYork  [1008, 1010, 1007]

In [260]:
df1.explode('Order_ID')

      City Order_ID
0       LA     1001
0       LA     1002
0       LA     1003
1   Madrid     1004
1   Madrid     1005
2  NewYork     1008
2  NewYork     1010
2  NewYork     1007

In [261]:
df1.explode('Order_ID').merge(df,on='Order_ID',how='left')

,City,Order_ID,Product,Price,Quantity,Order_Date,Customer_Email,Customer Name
0,LA,1001,Smartphone,599.99,2,2023-01-15,alice@example.com,alice
1,LA,1002,Laptop,899.00,1,2023-02-20,bob@example.com,bob
2,LA,1003,Headphones,150.00,5,2023-03-25,charlie@example.com,charlie
3,Madrid,1004,Smartphone,599.99,7,2023-01-15,alice@example.com,alice
4,Madrid,1005,Tablet,300.00,2,2023-05-05,eve@example.com,eve
5,NewYork,1008,Smartphone,300.00,3,2023-08-25,hank@example.com,hank
6,NewYork,1010,Mouse,15.00,1,2023-08-28,mickel@example.com,mickel
7,NewYork,1007,Smartwatch,599.99,3,2023-12-25,david@example.com,david

In [262]:
data={'Customer Name':['alice', 'bob', 'charlie', 'eve','david',
       'hank', 'mickel'],'Age':[22,25,33,26,31,35,42]}
df2=pd.DataFrame(data)
df2.head()

  Customer Name  Age
0         alice   22
1           bob   25
2       charlie   33
3           eve   26
4         david   31

In [263]:
df.merge(df2,on='Customer Name',how='left')

,Order_ID,Product,Price,Quantity,Order_Date,Customer_Email,Customer Name,Age
0,1001,Smartphone,599.99,2,2023-01-15,alice@example.com,alice,22
1,1002,Laptop,899.00,1,2023-02-20,bob@example.com,bob,25
2,1003,Headphones,150.00,5,2023-03-25,charlie@example.com,charlie,33
3,1004,Smartphone,599.99,7,2023-01-15,alice@example.com,alice,22
4,1005,Tablet,300.00,2,2023-05-05,eve@example.com,eve,26
5,1007,Smartwatch,599.99,3,2023-12-25,david@example.com,david,31
6,1008,Smartphone,300.00,3,2023-08-25,hank@example.com,hank,35
7,1010,Mouse,15.00,1,2023-08-28,mickel@example.com,mickel,42

In [264]:
time_in_website={"Time_in_website":[2,3,4,5,6,8,0.5,1]}
df3=pd.DataFrame(time_in_website)
df3

   Time_in_website
0              2.0
1              3.0
2              4.0
3              5.0
4              6.0
5              8.0
6              0.5
7              1.0

In [265]:
dfff=pd.concat([df,df3],axis=1)
dfff

,Order_ID,Product,Price,Quantity,Order_Date,Customer_Email,Customer Name,Time_in_website
0,1001,Smartphone,599.99,2,2023-01-15,alice@example.com,alice,2.0
1,1002,Laptop,899.00,1,2023-02-20,bob@example.com,bob,3.0
2,1003,Headphones,150.00,5,2023-03-25,charlie@example.com,charlie,4.0
3,1004,Smartphone,599.99,7,2023-01-15,alice@example.com,alice,5.0
4,1005,Tablet,300.00,2,2023-05-05,eve@example.com,eve,6.0
5,1007,Smartwatch,599.99,3,2023-12-25,david@example.com,david,8.0
6,1008,Smartphone,300.00,3,2023-08-25,hank@example.com,hank,0.5
7,1010,Mouse,15.00,1,2023-08-28,mickel@example.com,mickel,1.0

In [266]:
best_customer=['Boor','Medium','Good']
dfff['Best_Customer']=pd.qcut(dfff['Time_in_website'],q=3,labels=best_customer)
dfff

,Order_ID,Product,Price,Quantity,Order_Date,Customer_Email,Customer Name,Time_in_website,Best_Customer
0,1001,Smartphone,599.99,2,2023-01-15,alice@example.com,alice,2.0,Boor
1,1002,Laptop,899.00,1,2023-02-20,bob@example.com,bob,3.0,Medium
2,1003,Headphones,150.00,5,2023-03-25,charlie@example.com,charlie,4.0,Medium
3,1004,Smartphone,599.99,7,2023-01-15,alice@example.com,alice,5.0,Good
4,1005,Tablet,300.00,2,2023-05-05,eve@example.com,eve,6.0,Good
5,1007,Smartwatch,599.99,3,2023-12-25,david@example.com,david,8.0,Good
6,1008,Smartphone,300.00,3,2023-08-25,hank@example.com,hank,0.5,Boor
7,1010,Mouse,15.00,1,2023-08-28,mickel@example.com,mickel,1.0,Boor

# 12- Melting Data

In [267]:
#From Wide to long
df.melt(id_vars='Product',value_vars=['Quantity','Order_ID'])

       Product  variable  value
0   Smartphone  Quantity      2
1       Laptop  Quantity      1
2   Headphones  Quantity      5
3   Smartphone  Quantity      7
4       Tablet  Quantity      2
5   Smartwatch  Quantity      3
6   Smartphone  Quantity      3
7        Mouse  Quantity      1
8   Smartphone  Order_ID   1001
9       Laptop  Order_ID   1002
10  Headphones  Order_ID   1003
11  Smartphone  Order_ID   1004
12      Tablet  Order_ID   1005
13  Smartwatch  Order_ID   1007
14  Smartphone  Order_ID   1008
15       Mouse  Order_ID   1010

In [268]:
df.melt(id_vars=['Customer Name','Quantity'],value_vars='Price')

  Customer Name  Quantity variable   value
0         alice         2    Price  599.99
1           bob         1    Price  899.00
2       charlie         5    Price  150.00
3         alice         7    Price  599.99
4           eve         2    Price  300.00
5         david         3    Price  599.99
6          hank         3    Price  300.00
7        mickel         1    Price   15.00

In [269]:
df.melt(id_vars=['Customer Name'], value_vars='Order_ID', 
                               var_name='Product', value_name='order_id')

  Customer Name   Product  order_id
0         alice  Order_ID      1001
1           bob  Order_ID      1002
2       charlie  Order_ID      1003
3         alice  Order_ID      1004
4           eve  Order_ID      1005
5         david  Order_ID      1007
6          hank  Order_ID      1008
7        mickel  Order_ID      1010

In [270]:
df.melt(id_vars=['Customer Name','Order_ID'], value_vars='Price', 
                               var_name='Feature', value_name='price')

  Customer Name  Order_ID Feature   price
0         alice      1001   Price  599.99
1           bob      1002   Price  899.00
2       charlie      1003   Price  150.00
3         alice      1004   Price  599.99
4           eve      1005   Price  300.00
5         david      1007   Price  599.99
6          hank      1008   Price  300.00
7        mickel      1010   Price   15.00

In [271]:
df.melt(id_vars=['Customer Name'], value_vars=['Price','Order_ID'], 
                               var_name='Feature', value_name='price')

   Customer Name   Feature    price
0          alice     Price   599.99
1            bob     Price   899.00
2        charlie     Price   150.00
3          alice     Price   599.99
4            eve     Price   300.00
5          david     Price   599.99
6           hank     Price   300.00
7         mickel     Price    15.00
8          alice  Order_ID  1001.00
9            bob  Order_ID  1002.00
10       charlie  Order_ID  1003.00
11         alice  Order_ID  1004.00
12           eve  Order_ID  1005.00
13         david  Order_ID  1007.00
14          hank  Order_ID  1008.00
15        mickel  Order_ID  1010.00

# 13- Reshaping

In [272]:
#use sample of original dataframe to show affect of reshape
dff=df.iloc[:3,:]
dff.drop(['Order_Date','Customer_Email'],axis=1,inplace=True)
dff

   Order_ID     Product   Price  Quantity Customer Name
0      1001  Smartphone  599.99         2         alice
1      1002      Laptop  899.00         1           bob
2      1003  Headphones  150.00         5       charlie

In [273]:
dff.stack()

0  Order_ID               1001
   Product          Smartphone
   Price                599.99
   Quantity                  2
   Customer Name         alice
1  Order_ID               1002
   Product              Laptop
   Price                 899.0
   Quantity                  1
   Customer Name           bob
2  Order_ID               1003
   Product          Headphones
   Price                 150.0
   Quantity                  5
   Customer Name       charlie
dtype: object

In [274]:
dff.unstack()

Order_ID       0          1001
               1          1002
               2          1003
Product        0    Smartphone
               1        Laptop
               2    Headphones
Price          0        599.99
               1         899.0
               2         150.0
Quantity       0             2
               1             1
               2             5
Customer Name  0         alice
               1           bob
               2       charlie
dtype: object

In [275]:
dff.set_index(['Order_ID','Product']).stack()

Order_ID  Product
1001      Smartphone  Price             599.99
                      Quantity               2
                      Customer Name      alice
1002      Laptop      Price              899.0
                      Quantity               1
                      Customer Name        bob
1003      Headphones  Price              150.0
                      Quantity               5
                      Customer Name    charlie
dtype: object

In [276]:
p_v = dff.pivot_table(
    index='Customer Name',
    columns='Product',
    values='Quantity',
    aggfunc='sum'
)
p_v

Product        Headphones  Laptop  Smartphone
Customer Name
alice                <NA>    <NA>           2
bob                  <NA>       1        <NA>
charlie                 5    <NA>        <NA>

In [277]:
p_v.stack()

Customer Name  Product
alice          Smartphone    2
bob            Laptop        1
charlie        Headphones    5
dtype: Int64

In [278]:
p_v.stack().sum(axis=0)

8

In [279]:
p_v.stack().groupby(level='Product').sum()

Product
Headphones    5
Laptop        1
Smartphone    2
dtype: Int64

# 14- Save to CSV

In [280]:
df.to_csv('Order.csv', index=False, header=False)